name: CI
on:
  push:
    branches: [ '**' ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: handy-common-utils/automation/github/actions/prepare-node@main
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

  test:
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [ mocha, jest ]
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: cd ${{matrix.project}} ; npm test
        shell: bash
