name: CI
on:
  push:
    branches: ['**']

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: handy-common-utils/automation/github/actions/prepare-node@main
        with:
          node-version: .nvmrc
      - uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            */node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

  test:
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [common, dummy, mocha, jest]

    steps:
      - uses: handy-common-utils/automation/github/actions/prepare-node@main
        with:
          node-version: .nvmrc
      - uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            */node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm -w ${{matrix.project}} test
        shell: bash
