name: Release if needed
on:
  push:
    branches: [master, main]

jobs:
  release-if-needed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'
          cache-dependency-path: |
            package.json
            package-lock.json
      - run: npm ci
      - run: npx multi-semrel
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

